name: ar-editor-preview
slug: ar-editor-preview
description: ARCore/ARKit’s real-world AR data is sent to Unity Editor in LiveKit and Protocol ARKs。
description_ja: ARCore/ARKitの実機ARデータをLiveKitとProtocol BuffersでUnity Editorへ送信し、Unity上でARプレビューを行うためのマルチプラットフォーム開発環境。
translation_locked: false
status: incubating
repo: null
tags:
  - AR
  - Unity
  - ARCore
  - ARKit
  - LiveKit
  - Protocol Buffers
