name: attention-intervention-system
slug: attention-intervention-system
description: App that displays goals for lock screens and notifications and reminds you of your goals every time you see your smartphone
description_ja: ロック画面や通知に目標を表示し、スマートフォンを見るたびに目標を思い出せるアプリ
translation_locked: false
status: incubating
repo: null
tags: null
