name: noroshi-app
slug: noroshi-app
description: AR application that displays virtual smoke signals at specified locations, viewable through an AR camera.
description_ja: 指定した場所に狼煙を出現させ、ARカメラを通して見ると実際に狼煙が見える位置情報ベースのARアプリです。
translation_locked: false
status: incubating
repo: ''
tags:
  - ar
  - unity
  - cloudflare
  - drizzle
  - geohash
  - location
  - firebase
